image:
  file: gitpod/Dockerfile
tasks:
  - name: Install asdf .tool-versions
    init: |
      asdf install
  - name: Start docker-compose
    init: |
      docker-compose pull
    command: |
      docker-compose up -d
vscode:
  extensions:
    - JakeBecker.elixir-ls@0.2.25:X1tqg5Hmluq055QJpf0/7A==
    - mjmcloug.vscode-elixir@1.1.0:w8GjsJyyhVFmCZmBc2Ws7A==